include(joinpath(@__DIR__, "../service.jl"))
const lifecycle = EventService.feature_case("not_found")
perf_setup() = lifecycle.prepare()
perf_workload(state) = lifecycle.operation(state)
perf_oracle(state, result) = lifecycle.verify(state, result)
