# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/qualification"
    schedule:
      interval: "weekly"
